[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.129.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"
  [headers.values]
    # 明确指定允许的域名，而不是使用 "*"
    Access-Control-Allow-Origin = "https://yourwebsite.com" 
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://unpkg.com https://m.stripe.network 'sha256-/5Guo2nzv5n/w6ukZpOBZOtTJBJPSkJ6mhHpnBgm3Ls=' https://realtime.ably.io; 
      style-src 'self' https://m.stripe.network;
      connect-src 'self' https://realtime.ably.io;
      img-src 'self' data:;
      font-src 'self';
      frame-src 'self';
      media-src 'self';
      object-src 'none';
      # report-uri https://your-csp-report-endpoint.com/; # 替换为实际的端点
    """

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200
